### ISSUE TITLE
[OSQA-910] The Wiki page is not working (http://wiki.osqa.net/)

### ISSUE THREAD

**Issue by javierder** [dzone/osqa#473]
<b><i>[reporter="gandi", created="Sun, 4 Nov 2012 06:59:41 -0500"]</i></b>
I'm note sure whether this is the correct place however in the home page I didn't saw "Report issue" link. I think the wiki is not working from pretty long time.
<br/>
<br/>
The message I see is:
<br/>
Service Temporarily Unavailable
<br/>
<br/>
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

**Comment by mpschmid** [comment]
This old wiki is being replaced with new documentation at: http://answerhub.com/qa/spaces/221/osqa-documentation.html
