### ISSUE TITLE
Missing checkboxes in 'Notifications and subscriptions settings'.

### ISSUE THREAD

**Issue by carlospzlz** [dzone/osqa#517]
Shouldn't we need to add the BooleanField fields present in the model here:
https://github.com/dzone/osqa/blob/master/forum/models/user.py#L548

in the qanda.py form too?
https://github.com/dzone/osqa/blob/master/forum/forms/qanda.py#L354

Thanks,
Carlos

**Comment by aido123** [comment]
The BooleanField in the model (users.py) will automatically convert to a CheckBoxInput. You just need to add each of these to the to the fields array at https://github.com/dzone/osqa/blob/master/forum/forms/qanda.py#L357

e.g.

`        fields = ['enable_notifications', 'member_joins', 'new_question', 'new_question_watched_tags', 'subscribed_questions', 'notify_answers' , 'notify_reply_to_comments' , 'notify_comments_own_post' , 'notify_comments' , 'notify_accepted']
`

**Comment by carlospzlz** [comment]
Oh, I see. Thanks a lot for your reply, @aido123!

Carlos
