### ISSUE TITLE
Google Authentication through OpenID 2.0 has been deprecated so google authentication is not working

### ISSUE THREAD

**Issue by javimaravillas** [dzone/osqa#77]
Google Authentication through OpenID 2.0 has been deprecated.

https://developers.google.com/+/api/auth-migration#timetable

It is recommended to migrate to Google+ Sign-In.

**Comment by dgreene3p** [comment]
I have a working google+ authentication module that I will be sending in via pull request sortly

**Comment by javimaravillas** [comment]
Thanks dude!
